name: Bug report
description: Report a bug you've encountered
labels: ["🪲bug"]
projects: ["veritaware/6"]
assignees:
  - nidrax
type: Bug
body:
  - type: input
    id: version
    attributes:
      label: Besprited version
      description: Paste Besprited version down below. You'll find it in the bottom left corner when you open the software. If you're on a dev version, please specify the commit hash
      placeholder: e.g. "v1.2.3" or "4f7d0d7"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is and the steps to reproduce the behaviour, additional screenshots or videos to help explain your problem etc.
      placeholder: e.g. "When I try to export a sprite sheet, the software crashes\n\n1. Open Besprited\n2. Load a project\n3. Click on Export\n4. See error"
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: Environment info
      description: Your operative system (version, distribution etc.), CPU and GPU model.
      placeholder: e.g. "Windows 11\nIntel Core i7-9700K\nNVIDIA GeForce RTX 2070"
    validations:
      required: false
