name: Code quality
description: Have you seen bad code? Click here
labels: ["💩code-quality"]
projects: ["veritaware/6"]
type: Task
body:
  - type: textarea
    id: code-problem
    attributes:
      label: What's wrong with the code?
      description: A clear and concise description of the poor quality you've noticed
      placeholder: e.g. "The function X has too many parameters and is hard to understand"
    validations:
      required: true
  - type: textarea
    id: ql-detection
    attributes:
      label: How did you detect the issue?
      description: Was the issue detected by some automated tooling / AI, or found manually?
      placeholder: e.g. "Issue reported by GitHub CodeQL checker"
    validations:
      required: false
