name: Documentation
description: Something wrong with the docs? Tell us here
labels: ["📑docs"]
projects: ["veritaware/6"]
assignees:
  - copilot
type: Task
body:
  - type: textarea
    id: documentation-issue
    attributes:
      label: Documentation issue
      description: Please describe what's wrong with the documentation (please no walls of text :P)
      placeholder: e.g. "The installation guide is missing steps for macOS"
    validations:
      required: true
