name: Linux

on:
  push:
    branches: [ trunk ]
    tags:
      - '*'
  pull_request:
    branches: [ trunk ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-26.04
    if: ${{ !contains(github.event.head_commit.message, 'NO_SW_CHANGE') && !contains(github.event.pull_request.body, 'NO_SW_CHANGE') }}
    steps:
    - uses: actions/checkout@v6
      with:
          submodules: 'true'
    - name: Prepare environment and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install g++ libcurl4-gnutls-dev libfreetype6-dev libgif-dev libgtest-dev libjpeg-dev libpixman-1-dev libpng-dev libsdl2-dev libsdl2-image-dev libtinyxml2-dev libwebp-dev libx11-dev libxcursor-dev ninja-build libnode-dev zlib1g-dev libarchive-dev libfuse2
        pip install cmake
    - name: Check for git tag
      id: check_tag
      run: |
        TAG=$(git describe --exact-match --tags 2>/dev/null) || true
        if [ -n "$TAG" ]; then
          echo "has_tag=true" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        else
          echo "has_tag=false" >> $GITHUB_OUTPUT
        fi
    - name: Get short commit hash
      id: commit
      run: |
        SHORT_HASH=$(git rev-parse --short HEAD)
        echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT
    - name: Update config.h with commit hash
      run: |
        sed -i 's/"local build"/"${{ steps.commit.outputs.short_hash }}"/g' src/config.h
    - name: Generate Makefiles
      run: |
        mkdir build
        if [ "${{ steps.check_tag.outputs.has_tag }}" = "true" ]; then
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DRELEASE_TAG=ON
        else
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        fi
    - name: Build the binaries
      run: |
        ninja -C build besprited
        rm build/bin/gen
    - name: Package the AppImage
      run: |
        export ARCH="$(uname -m)"
        sh packaging/package_linux.sh
        mv build/bin/Besprited-anylinux-$ARCH.AppImage .
    - name: Upload artifacts
      if: runner.arch == 'X64'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.check_tag.outputs.has_tag == 'true' && format('besprited-{0}-linux-x86_64', steps.check_tag.outputs.tag) || 'besprited-linux-x86_64' }}
        path: Besprited-anylinux-x86_64.AppImage
        if-no-files-found: error
