name: Static Code Analysis

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  cppcheck:
    runs-on: ubuntu-26.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      uses: ./.github/actions/install-deps

    - name: Install cppcheck
      run: sudo apt install -y cppcheck

    - name: Git submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

    - name: Build the project (required to generate *.xml.h files)
      run: cd build && ninja besprited

    - name: Run cppcheck
      run: cd build && cmake --build . --target cppcheck
      continue-on-error: true

  clang-tidy:
    runs-on: ubuntu-26.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      uses: ./.github/actions/install-deps

    - name: Install clang-tidy
      run: sudo apt install -y clang-tidy

    - name: Git submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

    - name: Build the project (required to generate *.xml.h files)
      run: cd build && ninja besprited

    - name: Run clang-tidy
      run: cd build && cmake --build . --target clang-tidy
      continue-on-error: true

  gcc-analyzer:
    runs-on: ubuntu-26.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      uses: ./.github/actions/install-deps

    - name: Git submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

    - name: Build the project (required to generate *.xml.h files)
      run: cd build && ninja besprited

    - name: Run GCC with -fanalyzer
      run: cd build && cmake --build . --target gcc-analyzer
      continue-on-error: true
