name: Deliver submodules too on release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Checkout modules
        run: git submodule update --init --recursive

      - name: Create the ZIP package
        run: |
          ARCHIVE="besprited-${GITHUB_REF_NAME}-source-with-submodules.zip"
          git archive -o "$ARCHIVE" HEAD
          git submodule --quiet foreach 'cd "$toplevel" && zip -qruy "'"$PWD/$ARCHIVE"'" "$sm_path" -x "*/.git" "*/.git/*"'
          echo "archive=$ARCHIVE" >> "$GITHUB_ENV"

      - name: Release the artifacts
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.archive }}
          fail_on_unmatched_files: true
